use super::templates::{TEMPLATE_TOKEN_FILES, TEMPLATE_TOKEN_GENERICS};
use super::types::{
    GeneratedCommandDefinition, GeneratedSubcommandReport, GeneratedVariantDefinition,
};
use super::util::sanitize_id;
use crate::error::{io_err, CapTraceError};
use crate::fixture::{
    TOKEN_ARG, TOKEN_DATA, TOKEN_HEADER, TOKEN_IN_FILE, TOKEN_IN_FILE_2, TOKEN_KV, TOKEN_OUT_FILE,
    TOKEN_TMP_DIR, TOKEN_URL,
};
use sieve_types::{Capability, CommandKnowledge, Resource};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

pub fn write_definition_json(
    path: &Path,
    definition: &GeneratedCommandDefinition,
) -> Result<(), CapTraceError> {
    let encoded = serde_json::to_string_pretty(definition)
        .map_err(|err| CapTraceError::Io(err.to_string()))?;
    fs::write(path, encoded).map_err(io_err)
}

pub fn render_rust_snippet(command: &str, variants: &[GeneratedVariantDefinition]) -> String {
    let fn_name = format!(
        "summarize_{}_trace_generated",
        sanitize_id(command).replace('-', "_")
    );
    let mut out = String::new();
    out.push_str("// Generated by sieve-captrace.\n");
    out.push_str(
        "// Paste into crates/sieve-command-summaries/src/lib.rs and adapt matcher logic.\n",
    );
    out.push_str(&format!(
        "fn {fn_name}(argv: &[String]) -> Option<SummaryOutcome> {{\n"
    ));
    out.push_str("    fn captrace_template_token_matches(token: &str, value: &str) -> bool {\n");
    out.push_str("        match token {\n");
    out.push_str(&format!(
        "            {} => value.starts_with(\"http://\") || value.starts_with(\"https://\"),\n",
        rust_string_literal(TOKEN_URL)
    ));
    out.push_str(&format!(
        "            {} => value.contains(':'),\n",
        rust_string_literal(TOKEN_HEADER)
    ));
    out.push_str(&format!(
        "            {} => value.contains('='),\n",
        rust_string_literal(TOKEN_KV)
    ));
    out.push_str(&format!(
        "            {} | {} | {} | {} | {} | {} => !value.is_empty(),\n",
        rust_string_literal(TOKEN_TMP_DIR),
        rust_string_literal(TOKEN_IN_FILE),
        rust_string_literal(TOKEN_IN_FILE_2),
        rust_string_literal(TOKEN_OUT_FILE),
        rust_string_literal(TOKEN_DATA),
        rust_string_literal(TOKEN_ARG),
    ));
    out.push_str("            _ => false,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    fn captrace_arg_matches_template(expected: &str, actual: &str) -> bool {\n");
    out.push_str("        if expected == actual {\n");
    out.push_str("            return true;\n");
    out.push_str("        }\n");
    out.push_str("        for token in [\n");
    for token in TEMPLATE_TOKEN_FILES
        .iter()
        .chain(TEMPLATE_TOKEN_GENERICS.iter())
    {
        out.push_str(&format!("            {},\n", rust_string_literal(token)));
    }
    out.push_str("        ] {\n");
    out.push_str("            if expected == token {\n");
    out.push_str("                return captrace_template_token_matches(token, actual);\n");
    out.push_str("            }\n");
    out.push_str("            if let Some(index) = expected.find(token) {\n");
    out.push_str("                let prefix = &expected[..index];\n");
    out.push_str("                let suffix = &expected[index + token.len()..];\n");
    out.push_str(
        "                if actual.len() < prefix.len() + suffix.len() || !actual.starts_with(prefix) || !actual.ends_with(suffix) {\n",
    );
    out.push_str("                    continue;\n");
    out.push_str("                }\n");
    out.push_str(
        "                let middle = &actual[prefix.len()..actual.len().saturating_sub(suffix.len())];\n",
    );
    out.push_str("                return captrace_template_token_matches(token, middle);\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("        false\n");
    out.push_str("    }\n");
    out.push_str(
        "    fn captrace_argv_matches_template(template: &[&str], argv: &[String]) -> bool {\n",
    );
    out.push_str("        if template.len() != argv.len() {\n");
    out.push_str("            return false;\n");
    out.push_str("        }\n");
    out.push_str("        template\n");
    out.push_str("            .iter()\n");
    out.push_str("            .zip(argv.iter())\n");
    out.push_str(
        "            .all(|(expected, actual)| captrace_arg_matches_template(expected, actual))\n",
    );
    out.push_str("    }\n");
    for variant in variants {
        let outcome = &variant.summary_outcome;
        if outcome.knowledge == CommandKnowledge::Known && outcome.summary.is_none() {
            continue;
        }
        out.push_str(&format!(
            "    // case_id: {}\n",
            rust_string_literal(&variant.case_id)
        ));
        if let Some(trace_path) = &variant.trace_path {
            out.push_str(&format!(
                "    // trace_path: {}\n",
                rust_string_literal(trace_path)
            ));
        }
        out.push_str("    let template = &[\n");
        for arg in &variant.argv_template {
            out.push_str(&format!("        {},\n", rust_string_literal(arg)));
        }
        out.push_str("    ];\n");
        out.push_str("    if captrace_argv_matches_template(template, argv) {\n");
        out.push_str("        return Some(SummaryOutcome {\n");
        out.push_str(&format!(
            "            knowledge: CommandKnowledge::{},\n",
            command_knowledge_variant(outcome.knowledge)
        ));
        if let Some(summary) = &outcome.summary {
            out.push_str("            summary: Some(CommandSummary {\n");
            out.push_str("                required_capabilities: vec![\n");
            for capability in &summary.required_capabilities {
                out.push_str("                    Capability {\n");
                out.push_str(&format!(
                    "                        resource: Resource::{},\n",
                    resource_variant(capability.resource)
                ));
                out.push_str(&format!(
                    "                        action: Action::{},\n",
                    action_variant(capability.action)
                ));
                out.push_str(&format!(
                    "                        scope: {}.to_string(),\n",
                    rust_string_literal(&capability.scope)
                ));
                out.push_str("                    },\n");
            }
            out.push_str("                ],\n");
            out.push_str("                sink_checks: vec![\n");
            for check in &summary.sink_checks {
                out.push_str("                    SinkCheck {\n");
                out.push_str(&format!(
                    "                        argument_name: {}.to_string(),\n",
                    rust_string_literal(&check.argument_name)
                ));
                out.push_str(&format!(
                    "                        sink: SinkKey({}.to_string()),\n",
                    rust_string_literal(&check.sink.0)
                ));
                out.push_str(&format!(
                    "                        channel: SinkChannel::{:?},\n",
                    check.channel
                ));
                out.push_str("                        value_refs: vec![\n");
                for value_ref in &check.value_refs {
                    out.push_str(&format!(
                        "                            ValueRef({}.to_string()),\n",
                        rust_string_literal(&value_ref.0)
                    ));
                }
                out.push_str("                        ],\n");
                out.push_str("                    },\n");
            }
            out.push_str("                ],\n");
            out.push_str("                unsupported_flags: vec![\n");
            for flag in &summary.unsupported_flags {
                out.push_str(&format!(
                    "                    {}.to_string(),\n",
                    rust_string_literal(flag)
                ));
            }
            out.push_str("                ],\n");
            out.push_str("            }),\n");
        } else {
            out.push_str("            summary: None,\n");
        }
        match outcome.reason.as_deref() {
            Some(reason) => out.push_str(&format!(
                "            reason: Some({}.to_string()),\n",
                rust_string_literal(reason)
            )),
            None => out.push_str("            reason: None,\n"),
        }
        out.push_str("        });\n");
        out.push_str("    }\n");
        out.push('\n');
    }
    out.push_str("    None\n");
    out.push_str("}\n");
    out
}

pub(super) fn build_subcommand_reports(
    variants: &[GeneratedVariantDefinition],
) -> Vec<GeneratedSubcommandReport> {
    #[derive(Default)]
    struct ReportBuilder {
        command_path: Vec<String>,
        variant_count: usize,
        successful_variants: usize,
        failed_variants: usize,
        trace_error_count: usize,
        capability_union: BTreeMap<String, Capability>,
    }

    let mut by_path: BTreeMap<String, ReportBuilder> = BTreeMap::new();
    for variant in variants {
        let key = variant.command_path.join("\u{1f}");
        let report = by_path.entry(key).or_default();
        report.command_path = variant.command_path.clone();
        report.variant_count += 1;
        if variant.trace_error.is_some() {
            report.trace_error_count += 1;
        }
        if variant.exit_code == Some(0) {
            report.successful_variants += 1;
        } else {
            report.failed_variants += 1;
        }

        let summary = variant
            .summary_outcome
            .summary
            .as_ref()
            .or(variant.trace_derived_summary.as_ref());
        if let Some(summary) = summary {
            for capability in &summary.required_capabilities {
                let cap_key = format!(
                    "{:?}\u{1f}{:?}\u{1f}{}",
                    capability.resource, capability.action, capability.scope
                );
                report
                    .capability_union
                    .entry(cap_key)
                    .or_insert_with(|| capability.clone());
            }
        }
    }

    by_path
        .into_values()
        .map(|builder| GeneratedSubcommandReport {
            command_path: builder.command_path,
            variant_count: builder.variant_count,
            successful_variants: builder.successful_variants,
            failed_variants: builder.failed_variants,
            trace_error_count: builder.trace_error_count,
            required_capabilities_union: builder.capability_union.into_values().collect(),
        })
        .collect()
}

fn resource_variant(resource: Resource) -> &'static str {
    match resource {
        Resource::Fs => "Fs",
        Resource::Net => "Net",
        Resource::Proc => "Proc",
        Resource::Env => "Env",
        Resource::Ipc => "Ipc",
    }
}

fn command_knowledge_variant(knowledge: CommandKnowledge) -> &'static str {
    match knowledge {
        CommandKnowledge::Known => "Known",
        CommandKnowledge::Unknown => "Unknown",
        CommandKnowledge::Uncertain => "Uncertain",
    }
}

fn action_variant(action: sieve_types::Action) -> &'static str {
    match action {
        sieve_types::Action::Read => "Read",
        sieve_types::Action::Write => "Write",
        sieve_types::Action::Append => "Append",
        sieve_types::Action::Exec => "Exec",
        sieve_types::Action::Connect => "Connect",
    }
}

fn rust_string_literal(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
